# Generated by Django 4.0.4 on 2022-05-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cover',
        ),
    ]
